# =============================================================================
# Terraform-docs Configuration
# =============================================================================
#
# This file configures automatic documentation generation for Terraform modules.
#
# Usage:
#   terraform-docs markdown . > README.md
#   terraform-docs markdown table --output-file README.md .
#
# =============================================================================

formatter: markdown table

version: ">= 0.17.0"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
